name: .NET

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [  ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT: ./src/backend.api/backend.csproj
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore $PROJECT
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
    - name: Build
      run: dotnet publish --no-restore -c Release -o $(pwd)/publish $PROJECT
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: givt/givt-rag-api:main
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}
    - name: Restart container
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az account set -s 2a3aee87-edae-4b99-bd95-8f57e5c58a97
          az container restart --name givt-debug-rag-backend --resource-group givt-debug-rag
