name: .NET

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [  ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT: ./src/backend.api/backend.csproj
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore $PROJECT
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
    - name: Build
      run: dotnet publish --no-restore -c Release -o $(pwd)/publish $PROJECT
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: givt/givt-rag-api:main
    - name: Azure CLI Install
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - name: Azure login and restart container
      env:
        AZURE_PRINCIPAL_SECRET_DEV: ${{ secrets.AZURE_PRINCIPAL_SECRET_DEV }}
        TENANT_ID: 06b7c88c-86d5-413f-8ca3-129402419237
        CLIENT_ID: 88015dd8-4087-4c6c-9a8c-ec93e2c93571
        SUBSCRIPTION_ID: 2a3aee87-edae-4b99-bd95-8f57e5c58a97
      run: |
        az login --service-principal --tenant ${TENANT_ID} -u ${CLIENT_ID} -p ${AZURE_PRINCIPAL_SECRET_DEV}
        az account set -s ${SUBSCRIPTION_ID}
    - name: Azure restart container # make sure IAM is configured for service principal!
      env:
        CONTAINER_NAME: givt-debug-rag-backend
        RESOURCE_GROUP: givt-debug-rag
      run: az container restart --name ${CONTAINER_NAME} --resource-group ${RESOURCE_GROUP}
