name: .NET

on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [  ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT: ./src/backend.api/backend.csproj
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore $PROJECT
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
    - name: Build
      run: dotnet publish --no-restore -r linux-x64 -f net5.0 -c Release -o $(pwd)/publish $PROJECT
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: givt/givt-rag-api:main
